owner: hatamiarash7
repo: MyWebSite_Status
user-agent: hatamiarash7

sites:
  - name: Main Website
    url: https://arash-hatami.ir
  - name: Portfolio
    url: https://portfolio.arash-hatami.ir
  - name: DNS Lookup
    url: https://dns.arash-hatami.ir
  - name: Status Page
    url: https://status.arash-hatami.ir
  - name: Analytics Server
    url: https://matomo.arash-hatami.ir/matomo.php
    expectedStatusCodes:
      - 200
  - name: Analytics Server - API
    url: https://matomo.arash-hatami.ir/index.php?module=API&method=API.getMatomoVersion&token_auth=$MATOMO_API_KEY
    expectedStatusCodes:
      - 200
  - name: Comment Server
    url: https://isso.arash-hatami.ir
    expectedStatusCodes:
      - 200
      - 201
      - 400
  - name: Git Server
    url: https://git.arash-hatami.ir
  - name: Code Guide
    url: https://cg.arash-hatami.ir
  - name: Nikas
    url: https://nikasproject.ir
  - name: Periodic Table
    url: https://periodic.arash-hatami.ir
  - name: Audio Visualization
    url: https://audiovisualization.arash-hatami.ir

assignees:
  - hatamiarash7

status-website:
  theme: light
  cname: status.arash-hatami.ir
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Arash Hatami
  introTitle: "Arash Hatami"
  introMessage: Status Page
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER
    - title: Website
      href: https://arash-hatami.ir
    - title: Projects
      href: https://portfolio.arash-hatami.ir

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

i18n:
  footer: Developed with 🖤 in this chaotic world!
