owner: hatamiarash7
repo: MyWebSite_Status

# Add your sites here
sites:
  - name: Main Website
    url: https://arash-hatami.ir

status-website:
  cname: status.arash-hatami.ir
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Arash Hatami"
  introMessage: Status Page
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
